### ISSUE TITLE
More permissions

### ISSUE THREAD

**Issue by rErEaT** [h1karo/ShareControl#6]
How I can add a permission to craft in creative?:D

**Comment by h1karo** [comment]
For what?

**Comment by rErEaT** [comment]
for DiceFurniture, or any other plugin what has new craftable items

**Comment by h1karo** [comment]
Why the player in creative mode to craft anything? The whole point of a plugin that player in creative mode was engaged only in construction, but things are not collected in the chest.

**Comment by rErEaT** [comment]
Sure, I just need a permission what allow to craft :D

nothing more, cause I have some + craftable items what I wanna allow in creative worlds

**Comment by h1karo** [comment]
It is impossible, as the craft table is prohibited, it is implements. If the player gets access to it, you will be able to throw things through him, leaving them in and pressing the ESC.

**Comment by rErEaT** [comment]
https://www.spigotmc.org/resources/creativecontrolbykubqoa.9988/

its make it, bug a lots of error in console

**Comment by rErEaT** [comment]
In creative the players can plant :O

**Comment by h1karo** [comment]
Players can be planted, but the plants do not start dropping. And do permission to access the containers pointless, given that it will allow players to shift blocks of creativity in survival mode. In this case, the plugin general unnecessary, just load on the server.

**Comment by rErEaT** [comment]
sugar cane.
drop the item
